### ISSUE TITLE
Development Process

### ISSUE THREAD

**Issue by rainyrainyguo** [CS130-W20/team-A3#18]
## Description
what is the general development process of the project?

## Additional Context
From my understanding, our goal is to have each module implemented by one team member. Therefore:
1. each one can set up a branch. 
2. Before the implementation of a feature, we open an issue (user story) on Github as a checklist. 
3. We commit small changes locally, push large changes to Github under our own branch. When we finish a feature, send a pull request to ask for merging. After successful testing, the branch can be merged. Then the corresponding issue can be closed.

## Relevant screenshots
Please add more details or correct me if I am not understanding correctly.

**Comment by yugowatanabe** [comment]
Agreed, looks like we've been doing ok doing that so far. I've been pushing small changes directly to master
