### ISSUE TITLE
More Colors as the theme 

### ISSUE THREAD

**Issue by KeplerC** [CS130-W20/team-A3#20]
## User Story
As a user, I would like to see more colors in the webpage so that it looks better.

## Detailed Description
This is the comment provided in the report. Will use a better design on this one. 
However, it is indeed not our top priority

## Acceptance Criteria
- [ ] Given the webpage, then give a better visualization

**Comment by rainyrainyguo** [comment]
If we want to make the webpage more colourful, do we have to switch to another CSS template or just adding more colour to the current template? 
However, in my own opinion, maybe it is better for an educational website to keep simple and straightforward?

**Comment by KeplerC** [comment]
Indeed, I don't think it is a top priority. I was just to reflect our comments. I will go ahead and close the issue.

**Comment by zijie2333** [comment]
I think we are doing great on the current webpage style design
