### ISSUE TITLE
 [QUESTION] - Readme.txt

### ISSUE THREAD

**Issue by songjiang0909** [CS130-W20/team-A3#44]
## User Story
Readme.txt

## Detailed Description
Please add the code structure introduction in the readme file.
## Acceptance Criteria
- [ ] Add all code structure for each part
- [ ] Add code description.

**Comment by KeplerC** [comment]
I can work on this. but I think we need to finish the report(part c) first

**Comment by rainyrainyguo** [comment]
Maybe we can have a skeleton and let everyone finish their own part.
