### ISSUE TITLE
[QUESTION] - Search Filtering and Search Ranking

### ISSUE THREAD

**Issue by rainyrainyguo** [CS130-W20/team-A3#48]
## Description
The workflow of search is unclear now. We need to distinguish when to do search filtering and when to do search ranking. 

## Relevant screenshots
Current version:
1. From the homepage, user types in keywords in the search bar and choose which **filter** to use.
![search1](https://user-images.githubusercontent.com/32846406/74901402-a0028000-5357-11ea-91c2-b6d2adbd781c.png)
2. After being redirected to the course content page. On the top of the page, there are different choices of **ranking** strategy: Relevance & Hot.
![search2](https://user-images.githubusercontent.com/32846406/74901505-e48e1b80-5357-11ea-8857-2a7fe43d5672.png)

## Additional Context
I personally think the workflow should be changed in the following way:
1. On the home page, there should only be a search bar and **no filter or ranking strategy**
2. On the course content page, filter and ranking should both be provided. (The default display is based on Relevance and no filter)

Any comments and discussion are welcomed.

**Comment by zijie2333** [comment]
I think search by field should be kept as it would allow users to make a more precise search.
However I think what can be added is a search meta bar. For example when you first search AI, it returns 100 courses, then you search NLP based on it , it returns 35 courses... There can be a bar that shows your search meta path.

**Comment by songjiang0909** [comment]
I agree with Zijie
