### ISSUE TITLE
[BUG] - Search Mode

### ISSUE THREAD

**Issue by zijie2333** [CS130-W20/team-A3#55]
## Description
The left side bar on search mode is not clickable. Should fix it.

## Expected Behavior
Given a click on the left side bar, return to the corresponding category info page.

## Relevant screenshots

![image](https://user-images.githubusercontent.com/20399545/74914730-cc2df900-5377-11ea-84cc-09587a852110.png)

**Comment by rainyrainyguo** [comment]
It works for me? Maybe reload the page and try again?

**Comment by zijie2333** [comment]
Can close the issue, because in the search page, the left-side navigation bar is for user to better search, no need to redirect to the corresponding category info page.
