### ISSUE TITLE
[QUESTION] - Any problems in the deployed version?

### ISSUE THREAD

**Issue by songjiang0909** [CS130-W20/team-A3#64]
## Description
Hi, please help to check whether there are any problems in the deployed version.

**Comment by rainyrainyguo** [comment]
The "view details" part in the home page does not work sometimes.
![image](https://user-images.githubusercontent.com/32846406/76185941-e9433400-618d-11ea-9f2f-be493e101991.png)

**Comment by zijie2333** [comment]
Is data mining the example doesn’t work? Actually it is because the loading is slow…I just tried and it is okay on data mining

**Comment by rainyrainyguo** [comment]
I think it is not becuase of speed. Sometimes it gives an error page. But it does not occur very often.
